/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: haykel-shaba (https://sketchfab.com/haykel1993)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/soccer-football-stadium-game-asset-lowpoly-city-73de63c7cf3f4a238bb334976d4b58d2
Title: ⚽Soccer football stadium game asset lowpoly city
*/

import scene from '/src/assets/soccer.glb'

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { useNavigate } from 'react-router-dom'
import { HomeText } from '../components/HomeText'

export function Soccer(props) {
    const { nodes, materials } = useGLTF(scene)
    const soccerRef = useRef()
    const navigate = useNavigate()

  const [zoomIn, setZoomIn] = useState(false)
  const [zoomComplete, setZoomComplete] = useState(false)
  const { gl, viewport } = useThree();
  
  const handleClick = (e) => {
    setZoomIn(true)
  }

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener("click", handleClick);

    return () => {
      canvas.removeEventListener("click", handleClick);
    };
  }, [gl, handleClick]);

  useEffect(() => {
    if (zoomComplete) {
      navigate('/about', { replace: true })    
    }
  }, [zoomComplete]);

const targetPositions = {
    x: 0.5,
    y: -0.5,
    z: 6.7,
    rotationX: -1.5
};

// Calculate distances to be covered in each dimension
const distances = {
    x: Math.abs(targetPositions.x - 1.2),
    y: Math.abs(targetPositions.y - (-0.9)),
    z: Math.abs(targetPositions.z - 2),
    rotationX: Math.abs(targetPositions.rotationX - 0.2)
};

// Find the maximum distance
const maxDistance = Math.max(distances.x, distances.y, distances.z, distances.rotationX);

// Calculate rates of change in each dimension
const rates = {
    x: distances.x / maxDistance * 0.035,
    y: distances.y / maxDistance * 0.0,
    z: distances.z / maxDistance * 0.035,
    rotationX: distances.rotationX / maxDistance * 0.03,
};

  useFrame(() => {
    if (zoomIn) {
        if (soccerRef.current.position.z < 6.7) {
            soccerRef.current.position.z += rates.z
        }
        if (soccerRef.current.position.x > 0.5) {
            soccerRef.current.position.x -= rates.x
        }
        if (soccerRef.current.position.y < -0.5) {
            soccerRef.current.position.y += rates.y
        }
         if (soccerRef.current.rotation.x > -1.5) {
          soccerRef.current.rotation.x -= rates.rotationX;
        }

        // Check if all conditions are satisfied
        const allConditionsMet =
            soccerRef.current.position.z >= 6.7 &&
            soccerRef.current.position.x <= 0.5 &&
            soccerRef.current.rotation.x >= -2;

        if (allConditionsMet) {
          setTimeout(() => {
            setZoomComplete(true);
          }, 500); // 0.5 second delay
        }
        }
    });
    
  return (
    <>
    {!zoomIn && (
      <Html>
      <div className="absolute transform -translate-x-1/2 -translate-y-80 z-10 w-80">
        <HomeText />
      </div>
    </Html>
    ) }
    <group ref={soccerRef}  {...props} dispose={null}>
      <group
        position={[-2.416, 0.362, -1.809]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.025, 0.007, 0.025]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-2.416, 0.362, -0.919]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.025, 0.007, 0.025]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-2.416, 0.208, 0.209]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.025, 0.007, 0.025]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-2.404, 0.547, 0.328]}
        rotation={[0, 0.867, -Math.PI / 2]}
        scale={[0.005, 0.255, 0.005]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_30.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_31.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-2.416, 0.362, 1.886]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.025, 0.007, 0.025]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_39.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_40.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[2.503, 0.362, -1.81]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.025, 0.007, 0.025]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_44.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_45.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[2.503, 0.362, -0.918]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.025, 0.007, 0.025]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_49.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_50.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[2.503, 0.208, 0.182]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.025, 0.007, 0.025]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_52.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_53.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[2.491, 0.547, 0.063]}
        rotation={[Math.PI, -0.867, Math.PI / 2]}
        scale={[0.005, 0.255, 0.005]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_57.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[2.503, 0.362, 1.886]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.025, 0.007, 0.025]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_66.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_67.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group position={[1.08, 0.208, -2.287]} scale={[0.025, 0.007, 0.025]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_159.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_160.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[0.961, 0.547, -2.275]}
        rotation={[0, -0.704, -Math.PI / 2]}
        scale={[0.005, 0.255, 0.005]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_164.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_165.geometry}
          material={materials['Material.002']}
        />
      </group>
      
      <group position={[-2.036, 0.362, -2.297]} scale={[0.025, 0.007, 0.025]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_574.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_575.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group position={[2.009, 0.362, -2.3]} scale={[0.025, 0.007, 0.025]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_579.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_580.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group position={[0.479, 0.574, -2.148]} rotation={[-1.4, 0, 0]} scale={0.005}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_645.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_646.geometry}
          material={materials['Material.004']}
        />
      </group>
      <group position={[-0.452, 0.574, 2.854]} rotation={[-1.742, 0, -Math.PI]} scale={0.005}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_648.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_649.geometry}
          material={materials['Material.004']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Material.001']}
        position={[0.015, 0.021, 0.363]}
        rotation={[-Math.PI, 0, 0]}
        scale={[5.517, 4.12, 4.461]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['Material.001']}
        position={[0, 0.009, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials['Material.001']}
        position={[-1.127, 0.09, -2.284]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials['Material.001']}
        position={[0, 0.428, -2.284]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials['Material.001']}
        position={[-2.399, 0.09, -1.81]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials['Material.001']}
        position={[-2.399, 0.09, -0.919]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials['Material.001']}
        position={[-2.408, 0.292, 0.21]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[0.005, 0.278, 0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_33.geometry}
        material={materials['Material.001']}
        position={[-2.399, 0.428, -0.37]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.154, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_35.geometry}
        material={materials['Material.001']}
        position={[-2.399, 0.428, 0.758]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.154, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_37.geometry}
        material={materials['Material.001']}
        position={[-2.399, 0.09, 1.886]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials['Material.001']}
        position={[2.487, 0.09, -1.809]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_47.geometry}
        material={materials['Material.001']}
        position={[2.487, 0.09, -0.917]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_55.geometry}
        material={materials['Material.001']}
        position={[2.496, 0.292, 0.18]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.005, 0.278, 0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials['Material.001']}
        position={[2.487, 0.428, 0.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.154, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials['Material.001']}
        position={[2.487, 0.428, -0.367]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.154, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_64.geometry}
        material={materials['Material.001']}
        position={[2.487, 0.09, 1.886]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_69.geometry}
        material={materials['Material.001']}
        position={[3.09, 0.8, -2.688]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.044, 0.017, 0.044]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_71.geometry}
        material={materials['Material.001']}
        position={[3.144, 1.631, -2.668]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_73.geometry}
        material={materials['Material.001']}
        position={[3.151, 1.631, 0.208]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_75.geometry}
        material={materials['Material.001']}
        position={[-3.045, 0.8, -2.688]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.044, 0.017, 0.044]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_77.geometry}
        material={materials['Material.001']}
        position={[-2.991, 1.631, -2.668]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_79.geometry}
        material={materials['Material.001']}
        position={[-2.984, 1.631, 0.208]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_105.geometry}
        material={materials['Material.001']}
        position={[-1.856, 0.102, -2.109]}
        scale={0.014}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_107.geometry}
        material={materials['Material.001']}
        position={[-1.751, 0.239, -2.097]}
        scale={1.186}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_109.geometry}
        material={materials['Material.001']}
        position={[0, -0.019, 0]}
        scale={[2.935, 2.195, 2.935]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_123.geometry}
        material={materials['Material.001']}
        position={[1.654, 0.111, 2.799]}
        rotation={[Math.PI / 2, 0, -1.701]}
        scale={[0.012, 0.058, 0.012]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_125.geometry}
        material={materials['Material.001']}
        position={[-1.771, 0, -3.403]}
        rotation={[Math.PI / 2, 0, -1.916]}
        scale={0.521}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_127.geometry}
        material={materials['Material.001']}
        position={[-1.769, 0.179, -3.343]}
        rotation={[Math.PI / 2, 0, -1.916]}
        scale={0.557}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_129.geometry}
        material={materials['Material.001']}
        position={[-1.769, 0.179, -3.343]}
        rotation={[Math.PI / 2, 0, -1.916]}
        scale={0.557}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_131.geometry}
        material={materials.grass}
        position={[-3.266, 0.084, -2.615]}
        rotation={[Math.PI / 2, 0, 2.697]}
        scale={0.158}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_133.geometry}
        material={materials.grass}
        position={[-3.188, 0.084, -2.652]}
        rotation={[Math.PI / 2, 0, 2.697]}
        scale={0.158}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_135.geometry}
        material={materials.grass}
        position={[-1.606, 0.136, -3.331]}
        rotation={[Math.PI / 2, 0, 2.635]}
        scale={0.303}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_137.geometry}
        material={materials.grass}
        position={[-1.225, 0.099, -3.407]}
        rotation={[Math.PI / 2, 0, -3.077]}
        scale={0.187}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_139.geometry}
        material={materials['Material.001']}
        position={[1.862, 0, -3.659]}
        rotation={[Math.PI / 2, 0, 1.317]}
        scale={0.462}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_141.geometry}
        material={materials['Material.001']}
        position={[1.862, 0, -3.659]}
        rotation={[Math.PI / 2, 0, 1.317]}
        scale={0.462}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_143.geometry}
        material={materials['Material.001']}
        position={[1.699, 0.179, -3.699]}
        rotation={[Math.PI / 2, 0, 1.317]}
        scale={0.557}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_145.geometry}
        material={materials['Material.001']}
        position={[1.699, 0.179, -3.699]}
        rotation={[Math.PI / 2, 0, 1.317]}
        scale={0.557}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_147.geometry}
        material={materials['Material.001']}
        position={[-3.744, 0, -0.265]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={0.557}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_149.geometry}
        material={materials['Material.001']}
        position={[-3.744, 0, -0.265]}
        rotation={[Math.PI / 2, 0, 3.12]}
        scale={0.557}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_151.geometry}
        material={materials['Material.001']}
        position={[-3.246, 0.516, -3.415]}
        rotation={[Math.PI / 2, 0, 2.912]}
        scale={0.827}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_153.geometry}
        material={materials['Material.001']}
        position={[-3.225, 0.723, -3.473]}
        rotation={[Math.PI / 2, 0, 2.912]}
        scale={0.827}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_155.geometry}
        material={materials['Material.001']}
        position={[3.528, 0.601, -2.132]}
        rotation={[Math.PI / 2, 0, -1.916]}
        scale={0.927}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_157.geometry}
        material={materials['Material.001']}
        position={[3.596, 0.833, -2.117]}
        rotation={[Math.PI / 2, 0, -1.916]}
        scale={0.927}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_162.geometry}
        material={materials['Material.001']}
        position={[1.079, 0.292, -2.28]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.005, 0.278, 0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_167.geometry}
        material={materials['Material.001']}
        position={[1.46, 0.428, -2.288]}
        scale={[0.154, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_169.geometry}
        material={materials['Material.001']}
        position={[1.511, 0.168, -9.125]}
        rotation={[Math.PI / 2, 0, 0.769]}
        scale={0.443}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_171.geometry}
        material={materials['Material.001']}
        position={[1.511, 0.168, -9.125]}
        rotation={[Math.PI / 2, 0, 0.769]}
        scale={0.443}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_173.geometry}
        material={materials['Material.001']}
        position={[-2.142, 0.473, -8.146]}
        rotation={[Math.PI / 2, 0, -0.775]}
        scale={0.73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_175.geometry}
        material={materials['Material.001']}
        position={[-2.131, 0.656, -8.093]}
        rotation={[Math.PI / 2, 0, -0.775]}
        scale={0.73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_177.geometry}
        material={materials['Material.001']}
        position={[2.487, 0.583, 2.862]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.154, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_179.geometry}
        material={materials['Material.001']}
        position={[-2.399, 0.583, 2.423]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.154, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_181.geometry}
        material={materials['Material.001']}
        position={[5.041, 0.808, 0.902]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_183.geometry}
        material={materials['Material.001']}
        position={[5.041, 0.808, 2.381]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_185.geometry}
        material={materials['Material.001']}
        position={[4.882, 0.83, -2.334]}
        scale={[0.331, 0.511, 0.331]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_187.geometry}
        material={materials['Material.001']}
        position={[4.882, 1.159, -2.334]}
        scale={[0.265, 0.41, 0.265]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_189.geometry}
        material={materials['Material.001']}
        position={[5.041, 1.39, -1.401]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_191.geometry}
        material={materials['Material.001']}
        position={[5.041, 2.585, -1.401]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.399, 0.617, 0.399]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_193.geometry}
        material={materials['Material.001']}
        position={[4.763, 1.997, 0.565]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.009, 0.225, 0.009]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_207.geometry}
        material={materials['Material.001']}
        position={[4.739, 1.632, -2.173]}
        rotation={[0, 1.049, 0]}
        scale={[0.01, 0.099, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_209.geometry}
        material={materials['Material.001']}
        position={[5, 3.989, -1.554]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.006, 0.271, 0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_211.geometry}
        material={materials['Material.001']}
        position={[5, 3.989, -1.113]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.006, 0.271, 0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_213.geometry}
        material={materials['Material.001']}
        position={[5.041, 0.356, -0.234]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_215.geometry}
        material={materials['Material.001']}
        position={[2.721, 0.808, -7.425]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_217.geometry}
        material={materials['Material.001']}
        position={[2.721, 0.808, -5.946]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_219.geometry}
        material={materials['Material.001']}
        position={[2.443, 1.997, -7.762]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.009, 0.225, 0.009]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_221.geometry}
        material={materials['Material.001']}
        position={[2.858, 2.22, -5.757]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.009, 0.225, 0.009]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_223.geometry}
        material={materials['Material.001']}
        position={[2.622, 2.144, -6.219]}
        rotation={[0, -0.866, -Math.PI / 2]}
        scale={0.137}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_225.geometry}
        material={materials['Material.001']}
        position={[2.649, 2.017, -6.18]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.016, 0.155, 0.016]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_227.geometry}
        material={materials['Material.001']}
        position={[2.721, 0.356, -8.561]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_229.geometry}
        material={materials['Material.001']}
        position={[5.169, 1.39, -5.892]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_237.geometry}
        material={materials['Material.001']}
        position={[5.041, 0.356, -3.696]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.891, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_239.geometry}
        material={materials['Material.001']}
        position={[-3.24, 0.808, -7.276]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_241.geometry}
        material={materials['Material.001']}
        position={[-3.24, 0.808, -8.754]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_243.geometry}
        material={materials['Material.001']}
        position={[-5.066, 0.83, -4.04]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.331, 0.511, 0.331]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_245.geometry}
        material={materials['Material.001']}
        position={[-5.066, 1.159, -4.04]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.265, 0.41, 0.265]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_247.geometry}
        material={materials['Material.001']}
        position={[4.068, 1.745, -12.373]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.518, 0.801, 0.518]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_249.geometry}
        material={materials['Material.001']}
        position={[4.068, 2.945, -12.373]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.401, 0.619, 0.401]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_251.geometry}
        material={materials['Material.001']}
        position={[-2.962, 1.997, -6.939]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.009, 0.225, 0.009]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_253.geometry}
        material={materials['Material.001']}
        position={[-3.377, 2.22, -8.944]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.009, 0.225, 0.009]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_269.geometry}
        material={materials['Material.001']}
        position={[4.303, 4.355, -12.323]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.006, 0.272, 0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_271.geometry}
        material={materials['Material.001']}
        position={[-3.24, 0.356, -6.14]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_273.geometry}
        material={materials['Material.001']}
        position={[-5.226, 0.356, -2.678]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.891, 0.798, 0.516]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_275.geometry}
        material={materials['Material.001']}
        position={[-5.226, 0.808, -1.127]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_277.geometry}
        material={materials['Material.001']}
        position={[-4.948, 1.997, -0.79]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.009, 0.225, 0.009]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_279.geometry}
        material={materials['Material.001']}
        position={[-5.226, 0.356, 0.009]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_287.geometry}
        material={materials['Material.001']}
        position={[3.842, 0.356, -7.279]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.661, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_289.geometry}
        material={materials['Material.001']}
        position={[-5.831, 1.39, -8.698]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_295.geometry}
        material={materials['Material.001']}
        position={[-4.504, 0.356, -7.311]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.661, 0.798, 0.516]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_323.geometry}
        material={materials['Material.001']}
        position={[-4.66, 2.596, -12.7]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.019, 0.189, 0.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_325.geometry}
        material={materials['Material.001']}
        position={[-1.752, 0.568, -12.612]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.63, 0.975, 0.63]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_327.geometry}
        material={materials['Material.001']}
        position={[1.477, 1.12, -12.612]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.63, 0.975, 0.63]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_329.geometry}
        material={materials['Material.001']}
        position={[-0.329, 1.12, -12.612]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.63, 0.975, 0.63]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_331.geometry}
        material={materials['Material.001']}
        position={[1.889, 2.572, -12.952]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.011, 0.275, 0.011]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_333.geometry}
        material={materials['Material.001']}
        position={[-0.56, 2.844, -12.444]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.011, 0.275, 0.011]}
      />
      
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_339.geometry}
        material={materials['Material.001']}
        position={[2.865, 0.568, -12.612]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.63, 0.975, 0.63]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_343.geometry}
        material={materials['Material.001']}
        position={[-1.444, 2.595, -14.392]}
        rotation={[0, -0.254, 0]}
        scale={[0.34, 0.526, 0.34]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_349.geometry}
        material={materials['Material.001']}
        position={[-3.166, 0.838, -13.363]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.973, 1.505, 0.973]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_353.geometry}
        material={materials['Material.001']}
        position={[0.567, 1.168, -13.985]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.38, 0.587, 0.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_355.geometry}
        material={materials['Material.001']}
        position={[-2.221, 0.621, -6.347]}
        rotation={[Math.PI / 2, 0, -0.775]}
        scale={0.941}
      />
      
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_434.geometry}
        material={materials['Material.001']}
        position={[1.773, 2.016, 8.392]}
        rotation={[-Math.PI, 0.254, -Math.PI]}
        scale={[0.279, 0.431, 0.279]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_531.geometry}
        material={materials.Material}
        position={[-1.2, 0.144, -4.146]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.187, 0.008, 0.008]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_572.geometry}
        material={materials['Material.001']}
        position={[-2.019, 0.09, -2.281]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_577.geometry}
        material={materials['Material.001']}
        position={[2.01, 0.09, -2.284]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_598.geometry}
        material={materials['Material.001']}
        position={[-2.24, 0.09, -1.106]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[0.01, 0.052, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_600.geometry}
        material={materials['Material.001']}
        position={[-2.24, 0.09, 1.258]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[0.01, 0.052, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_602.geometry}
        material={materials['Material.001']}
        position={[2.284, 0.09, 1.73]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.052, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_604.geometry}
        material={materials['Material.001']}
        position={[2.284, 0.09, -1.151]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.052, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_608.geometry}
        material={materials['Material.001']}
        position={[-7.53, 1.89, -6.687]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.631, 0.975, 0.631]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_616.geometry}
        material={materials['Material.001']}
        position={[7.063, 2.386, -6.773]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.516, 0.798, 0.516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_622.geometry}
        material={materials['Material.001']}
        position={[7.063, 0.486, -6.773]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.785, 0.798, 0.785]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_651.geometry}
        material={materials.Soccer_Ball}
        position={[0.213, 0.151, -0.196]}
        rotation={[0, 0.326, 0]}
        scale={0.228}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_653.geometry}
        material={materials['Material.001']}
        position={[1.567, 0.2, -1.885]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.056}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_655.geometry}
        material={materials['Material.001']}
        position={[-1.515, 0.2, -1.879]}
        rotation={[Math.PI / 2, 0, 0.247]}
        scale={0.056}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_657.geometry}
        material={materials['Material.001']}
        position={[-1.515, 0.2, 2.618]}
        rotation={[Math.PI / 2, 0, 0.247]}
        scale={0.056}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_661.geometry}
        material={materials['Material.005']}
        position={[2.714, 1.106, -0.498]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_663.geometry}
        material={materials['Material.005']}
        position={[2.714, 1.106, -1.811]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_665.geometry}
        material={materials['Material.005']}
        position={[2.714, 1.106, 2.396]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_667.geometry}
        material={materials['Material.005']}
        position={[2.714, 1.106, 1.083]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_669.geometry}
        material={materials['Material.005']}
        position={[-2.648, 1.106, 1.083]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_671.geometry}
        material={materials['Material.005']}
        position={[-2.648, 1.106, 2.396]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_673.geometry}
        material={materials['Material.005']}
        position={[-2.648, 1.106, -1.811]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_675.geometry}
        material={materials['Material.005']}
        position={[-2.648, 1.106, -0.498]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_677.geometry}
        material={materials['Material.009']}
        position={[0.277, 0.14, -0.034]}
        rotation={[1.709, -0.096, 2.537]}
        scale={0.003}
      />
    </group>
    </>
  )
}

